version: "3.1"

services:
  recetas.app:
    container_name: recetas.app
    image: backend-recetas:latest
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8080
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 index.js
    environment:
      - PORT=8080
    depends_on:
      - recetas.pg
  recetas.pg:
    container_name: recetas.pg
    image: postgres:latest
    volumes:
      - /shared_folder/postgresql:/var/lib/postgresql
      - ./db/script:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=recetas.pg
      - POSTGRES_USER=recetas
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DATABASE=recetas
      - POSTGRES_PORT=5432
